version: '3.9'

services:
  yingxv:
    restart: 'always'
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: yingxv
    container_name: yingxv
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    driver: bridge
