version: '3.9'

services:
  yingxv:
    
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: ngekaworu/yingxv
    container_name: yingxv
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    driver: bridge
