name: GitHub Actions Demo
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # 开启 
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOYER }}
        password: ${{ secrets.DEPLOY_PWD }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: | 
          cd yingxv/docker
          sh boot.sh